version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password123
      - DB_NAME=hospital_db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups

  db:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=hospital_db
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data: